services:
  web:
    image: clyvanta-2-web:latest
    container_name: clyvanta-prod
    ports:
      - "80:3000"
    restart: always
    networks:
      - clyvanta-prod-network

networks:
  clyvanta-prod-network:
    driver: bridge
