services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: clyvanta-dev
    ports:
      - "3002:3000"
    volumes:
      - .:/app:cached                    # Mac performance optimization
      - /app/node_modules               # Prevent overwrite
      - /app/.next                      # Cache Next.js builds
    environment:
      - CHOKIDAR_USEPOLLING=true       # Fix hot reload on Mac
      - WATCHPACK_POLLING=true          # Additional polling fix
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - clyvanta-network
    command: npm run dev

networks:
  clyvanta-network:
    driver: bridge