services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cch-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached                    # Mac performance optimization
      - /app/node_modules               # Prevent overwrite
      - /app/.next                      # Cache Next.js builds
    env_file:
      - .env.local                      # Load local environment
    environment:
      - CHOKIDAR_USEPOLLING=true       # Fix hot reload on Mac
      - WATCHPACK_POLLING=true          # Additional polling fix
    restart: unless-stopped
    networks:
      - cch-network
    command: npm run dev

networks:
  cch-network:
    driver: bridge